=== pkrayzy/HostlistCompiler/src/schemas/configuration.schema.json
{
  "$id": "https://adguarad.com/hostlist-compiler.configuration.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Hostlist compiler configuration",
  "description": "Configuration for the hostlist compiler",
  "type": "object",
  "properties": {
    "name": {
      "description": "Filter list name",
      "type": "string",
      "minLength": 1
    },
    "description": {
      "description": "Filter list description",
      "type": "string"
    },
    "homepage": {
      "description": "Filter list homepage",
      "type": "string"
    },
    "license": {
      "description": "Filter list license",
      "type": "string"
    },
    "version": {
      "description": "Filter version",
      "type": "string"
    },
    "sources": {
      "description": "An array of the filter list sources",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/source"
      }
    },
    "transformations": {
      "description": "A list of the transformations that will be applied",
      "type": "array",
      "allOf": [
        {
          "not": {
            "allOf": [
              {
                "contains": {
                  "const": "Validate"
                }
              },
              {
                "contains": {
                  "const": "ValidateAllowIp"
                }
              }
            ]
          }
        },
        {
          "not": {
            "allOf": [
              {
                "contains": {
                  "const": "Validate"
                }
              },
              {
                "contains": {
                  "const": "ValidateAllowPublicSuffix"
                }
              }
            ]
          }
        },
        {
          "not": {
            "allOf": [
              {
                "contains": {
                  "const": "ValidateAllowIp"
                }
              },
              {
                "contains": {
                  "const": "ValidateAllowPublicSuffix"
                }
              }
            ]
          }
        }
      ],
      "items": {
        "type": "string",
        "enum": [
          "RemoveComments",
          "RemoveModifiers",
          "Compress",
          "Validate",
          "ValidateAllowIp",
          "ValidateAllowPublicSuffix",
          "Deduplicate",
          "InvertAllow",
          "RemoveEmptyLines",
          "TrimLines",
          "InsertFinalNewLine",
          "ConvertToAscii"
        ]
      }
    },
    "exclusions": {
      "description": "A list of rules (or wildcards) to exclude from the source.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "exclusions_sources": {
      "description": "An array of exclusions sources.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "inclusions": {
      "description": "A list of wildcards to include from the source. All rules that don't match these wildcards won't be included.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "inclusions_sources": {
      "description": "A list of files with inclusions.",
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "name",
    "sources"
  ],
  "additionalProperties": false,
  "definitions": {
    "source": {
      "description": "A source for the filter list",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the source",
          "type": "string",
          "minLength": 1
        },
        "source": {
          "description": "Path to a file or a URL",
          "type": "string",
          "minLength": 1
        },
        "type": {
          "description": "Type of the source",
          "type": "string",
          "enum": [
            "adblock",
            "hosts"
          ]
        },
        "transformations": {
          "description": "A list of the transformations that will be applied",
          "type": "array",
          "allOf": [
            {
              "not": {
                "allOf": [
                  {
                    "contains": {
                      "const": "Validate"
                    }
                  },
                  {
                    "contains": {
                      "const": "ValidateAllowIp"
                    }
                  }
                ]
              }
            },
            {
              "not": {
                "allOf": [
                  {
                    "contains": {
                      "const": "Validate"
                    }
                  },
                  {
                    "contains": {
                      "const": "ValidateAllowPublicSuffix"
                    }
                  }
                ]
              }
            },
            {
              "not": {
                "allOf": [
                  {
                    "contains": {
                      "const": "ValidateAllowIp"
                    }
                  },
                  {
                    "contains": {
                      "const": "ValidateAllowPublicSuffix"
                    }
                  }
                ]
              }
            }
          ],
          "items": {
            "type": "string",
            "enum": [
              "RemoveComments",
              "RemoveModifiers",
              "Compress",
              "Validate",
              "ValidateAllowIp",
              "ValidateAllowPublicSuffix",
              "Deduplicate",
              "InvertAllow",
              "RemoveEmptyLines",
              "TrimLines",
              "InsertFinalNewLine",
              "ConvertToAscii"
            ]
          }
        },
        "exclusions": {
          "description": "A list of rules (or wildcards) to exclude from the source.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "exclusions_sources": {
          "description": "An array of exclusions sources.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "inclusions": {
          "description": "A list of wildcards to include from the source. All rules that don't match these wildcards won't be included.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "inclusions_sources": {
          "description": "A list of files with inclusions.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "source"
      ],
      "additionalProperties": false
    }
  }
}

=== pkrayzy/HostlistCompiler/examples/scriptlets/configuration.json
{
  "name": "Scriptlets",
  "sources": [
    {
      "name": "Krayzylist",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/SourceLists/scriptlets.txt",
      "type": "adblock"
    }
  ],
  "exclusions_sources": [
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/SourceLists/exclusions.txt"
  ],
  "transformations": [
    "Deduplicate"
  ]
}

=== pkrayzy/HostlistCompiler/examples/OISD/configuration.json
{
  "name": "OISD",
  "description": "Filter composed from several other filters (English filter, Social media filter, Spyware filter, Mobile ads filter, EasyList and EasyPrivacy) and simplified specifically to be better compatible with DNS-level ad blocking.",
  "homepage": "https://github.com/AdguardTeam/AdguardSDNSFilter",
  "license": "GPLv3",
  "sources": [
    {
      "name": "https://small.oisd.nl",
      "source": "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt",
      "type": "adblock",
      "transformations": ["RemoveModifiers", "Compress", "Validate"]
    },
    {
      "name": "https://small.oisd.nl",
      "source": "https://raw.githubusercontent.com/brave/adblock-lists/refs/heads/master/brave-lists/brave-ios-specific.txt",
      "type": "adblock",
      "transformations": ["RemoveModifiers", "Compress", "Validate"]
    },
    {
      "name": "EasyPrivacy Admiral",
      "source": "https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers_admiral.txt",
      "type": "adblock",
      "transformations": ["RemoveModifiers", "Compress", "Validate"]
    }
  ],
  "transformations": ["Deduplicate", "Compress"],
  "exclusions_sources": [
        "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral.txt",
        "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral-native.txt",
        "https://raw.githubusercontent.com/nextdns/click-tracking-domains/main/domains",
        "https://raw.githubusercontent.com/pkrayzy/FiltersCompiler/master/filters/DNSexclusions.txt"
      ]
}

=== pkrayzy/HostlistCompiler/examples/ublock_privacy/configuration.json
{
  "name": "uBlock filters – Privacy",
  "sources": [
    {
      "name": "uBlock filters – Privacy",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/SourceLists/ublock_privacy.txt",
      "type": "adblock"
    }
  ],
  "exclusions_sources": [
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/SourceLists/filter.txt",
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/SourceLists/exclusions.txt"
  ],
  "transformations": [
    "Deduplicate"
  ]
}

=== pkrayzy/HostlistCompiler/examples/adguard/configuration.json
{
  "name": "AdGuard Base filters (Optimized)",
  "description": "Compilation of AdGuard Base Filters, Excluding Domains Blocked by DNS",
  "homepage": "https://github.com/AdguardTeam/AdguardSDNSFilter",
  "license": "GPLv3",
  "sources": [
    {
      "name": "EasyList",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/SourceLists/adguard.txt",
      "type": "adblock"
    },
    {
      "name": "AdGuard Privacy Protection filters",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/SourceLists/adguard_privacy.txt",
      "type": "adblock",
      "exclusions_sources": [
        "https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_ads.txt",
        "https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_clickthroughs.txt",
        "https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_microsites.txt",
        "https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_trackers.txt",
        "https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_mail_trackers.txt"
      ]
    },
    {
      "name": "AdGuard Annoyances filters",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/SourceLists/adguard_annoyances.txt",
      "type": "adblock"
    }
  ],
  "exclusions_sources": [
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/filter.txt",
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/SourceLists/exclusions.txt"
  ],
  "transformations": [
    "Deduplicate"
  ]
}

=== pkrayzy/HostlistCompiler/examples/quickfix/configuration.json
{
  "name": "Quick Fixes Filter",
  "description": "Filter to quickly resolve content filtering issues on popular websites without updating the extension",
  "homepage": "https://github.com/AdguardTeam/AdguardSDNSFilter",
  "license": "GPLv3",
  "sources": [
    {
      "name": "Krayzylist",
      "source": "https://raw.githubusercontent.com/pkrayzy/Krayzylist/main/Blocklist",
      "type": "adblock"
    },
    {
      "name": "uBlock",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/ublock.txt",
      "type": "adblock"
    },
    {
      "name": "Paywalls",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/paywalls.txt",
      "type": "adblock"
    }
  ],
  "exclusions_sources": [
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/filter.txt",
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/exclusions.txt"
  ],
  "transformations": [
    "Deduplicate"
  ]
}

=== pkrayzy/HostlistCompiler/examples/paywalls/configuration.json
{
  "name": "Krayzylist",
  "sources": [
    {
      "name": "Krayzylist",
      "source": "https://raw.githubusercontent.com/pkrayzy/Krayzylist/main/Blocklist",
      "type": "adblock"
    }
  ],
  "exclusions_sources": [
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/SourceLists/exclusions.txt"
  ],
  "transformations": [
    "Deduplicate"
  ]
}

=== pkrayzy/HostlistCompiler/examples/ublock/configuration.json
{
  "name": "uBlock filters",
  "sources": [
    {
      "name": "uBlock filters",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/SourceLists/ublock_filters.txt",
      "type": "adblock"
    }
  ],
  "exclusions_sources": [
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/SourceLists/filter.txt",
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/SourceLists/exclusions.txt"
  ],
  "transformations": [
    "Deduplicate"
  ]
}
